changelog:
  exclude:
    labels:
      - tagpr
  categories:
    - title: New features and enhancements
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
