name: testing

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          python-version: "3.13"
      - run: uv sync --extra testing --no-dev --frozen
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        env:
          SKIP: uv-lock

  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.13"]
        group: [1, 2, 3]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv sync --extra testing --no-dev --frozen
      - run: >-
          uv run --no-project pytest -v -n 4 --dist load --maxschedchunk=1
          --splits 3 --group ${{ matrix.group }} --splitting-algorithm least_duration
          tests

  ci:
    if: always()
    needs: [pre-commit, tests]
    runs-on: ubuntu-latest
    steps:
      - name: Check required jobs
        run: |
          test "${{ needs.pre-commit.result }}" = success
          test "${{ needs.tests.result }}" = success
